### ISSUE TITLE
Missing dbus dependency on Ubuntu 16.04 LTS?

### ISSUE THREAD

**Issue by aried3r** [chef-cookbooks/chef_hostname#25]
### Cookbook version
0.4.1 (haven't seen anything in 0.4.2 that would solve this)

### Chef-client version
12.13.37

### Platform Details
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-042stab120.5 x86_64)

### Scenario:
Setting the hostname doesn't work.

### Steps to Reproduce:
```Ruby
# Hostname Recipie
hostname 'my.hostname.com'
```
Command:
```
knife solo cook user@host
```

### Expected Result:
```
Recipe: host-setup::default
  * hostname[my.hostname.com] action set
    * ohai[reload hostname] action nothing (skipped due to action :nothing)
    * execute[set hostname to my.hostname.com] action run (skipped due to not_if)
    * file[/etc/hosts] action create (skipped due to not_if)
    * execute[hostnamectl set-hostname my.hostname.com] action run
      - execute hostnamectl set-hostname my.hostname.com
    * ohai[reload hostname] action reload
      - re-run ohai and merge results into node attributes
```

### Actual Result:
IP and hostname redacted.
```
Recipe: host-setup::default
  * hostname[my.hostname.com] action set
    * ohai[reload hostname] action nothing (skipped due to action :nothing)
    * execute[set hostname to my.hostname.com] action run
      - execute /bin/hostname my.hostname.com
    * file[/etc/hosts] action create
      - update content in file /etc/hosts from de3143 to aa08c1
      --- /etc/hosts	2016-11-10 11:50:46.961917679 +0100
      +++ /etc/.chef-hosts20161110-1946-npic5h	2016-11-10 15:26:33.666459534 +0100
      @@ -4,5 +4,5 @@
       ff02::2		ip6-allrouters

       # Auto-generated hostname. Please do not remove this comment.
      -555.555.555.555 super.cool.hoster.example.com supercoolhoster555555555555
      +555.555.555.555 my.hostname.com dev
    * execute[hostnamectl set-hostname my.hostname.com] action run

      ================================================================================
      Error executing action `run` on resource 'execute[hostnamectl set-hostname my.hostname.com]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of hostnamectl set-hostname my.hostname.com ----
      STDOUT:
      STDERR: Failed to create bus connection: No such file or directory
      ---- End output of hostnamectl set-hostname my.hostname.com ----
      Ran hostnamectl set-hostname my.hostname.com returned 1

      Cookbook Trace:
      ---------------
      /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
      /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
      /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
      /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
      /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
      /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:133:in `compile_and_converge_action'
      /root/chef-solo/local-mode-cache/cache/cookbooks/chef_hostname/resources/hostname.rb:200:in `block in after_created'
      /root/chef-solo/local-mode-cache/cache/cookbooks/chef_hostname/resources/hostname.rb:199:in `each'
      /root/chef-solo/local-mode-cache/cache/cookbooks/chef_hostname/resources/hostname.rb:199:in `after_created'
      /root/chef-solo/local-mode-cache/cache/cookbooks/host-setup/recipes/default.rb:13:in `from_file'
      /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'

      Resource Declaration:
      ---------------------
      # In /root/chef-solo/local-mode-cache/cache/cookbooks/chef_hostname/resources/hostname.rb

       81:         execute "hostnamectl set-hostname #{new_resource.hostname}" do
       82:           notifies :reload, "ohai[reload hostname]"
       83:           not_if { shell_out!("hostnamectl status", { :returns => [0, 1] }).stdout =~ /Static hostname:\s+#{new_resource.hostname}/ }
       84:         end
       85:       when ::File.exist?("/etc/hostname")

      Compiled Resource:
      ------------------
      # Declared in /root/chef-solo/local-mode-cache/cache/cookbooks/chef_hostname/resources/hostname.rb:81:in `block in class_from_file'

      execute("hostnamectl set-hostname my.hostname.com") do
        action [:run]
        retries 0
        retry_delay 2
        default_guard_interpreter :execute
        command "hostnamectl set-hostname my.hostname.com"
        backup 5
        returns 0
        declared_type :execute
        cookbook_name "host-setup"
        not_if { #code block }
      end

      Platform:
      ---------
      x86_64-linux

    * ohai[reload hostname] action reload
      - re-run ohai and merge results into node attributes

    ================================================================================
    Error executing action `set` on resource 'hostname[my.hostname.com]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    execute[hostnamectl set-hostname my.hostname.com] (/root/chef-solo/local-mode-cache/cache/cookbooks/chef_hostname/resources/hostname.rb line 81) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of hostnamectl set-hostname my.hostname.com ----
    STDOUT:
    STDERR: Failed to create bus connection: No such file or directory
    ---- End output of hostnamectl set-hostname my.hostname.com ----
    Ran hostnamectl set-hostname my.hostname.com returned 1

    Cookbook Trace:
    ---------------
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:133:in `compile_and_converge_action'
    /root/chef-solo/local-mode-cache/cache/cookbooks/chef_hostname/resources/hostname.rb:200:in `block in after_created'
    /root/chef-solo/local-mode-cache/cache/cookbooks/chef_hostname/resources/hostname.rb:199:in `each'
    /root/chef-solo/local-mode-cache/cache/cookbooks/chef_hostname/resources/hostname.rb:199:in `after_created'
    /root/chef-solo/local-mode-cache/cache/cookbooks/host-setup/recipes/default.rb:13:in `from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'

    Resource Declaration:
    ---------------------
    # In /root/chef-solo/local-mode-cache/cache/cookbooks/host-setup/recipes/default.rb

     13:   hostname 'my.hostname.com'
     14: end

    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/local-mode-cache/cache/cookbooks/host-setup/recipes/default.rb:13:in `from_file'

    hostname("my.hostname.com") do
      action [:set]
      updated true
      updated_by_last_action true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :hostname
      cookbook_name "host-setup"
      recipe_name "default"
      compile_time true
      hostname "my.hostname.com"
      ipaddress "555.555.555.555"
    end

    Platform:
    ---------
    x86_64-linux


  ================================================================================
  Recipe Compile Error in /root/chef-solo/local-mode-cache/cache/cookbooks/host-setup/recipes/default.rb
  ================================================================================

  Mixlib::ShellOut::ShellCommandFailed
  ------------------------------------
  hostname[my.hostname.com] (host-setup::default line 13) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[hostnamectl set-hostname my.hostname.com] (/root/chef-solo/local-mode-cache/cache/cookbooks/chef_hostname/resources/hostname.rb line 81) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
  ---- Begin output of hostnamectl set-hostname my.hostname.com ----
  STDOUT:
  STDERR: Failed to create bus connection: No such file or directory
  ---- End output of hostnamectl set-hostname my.hostname.com ----
  Ran hostnamectl set-hostname my.hostname.com returned 1

  Cookbook Trace:
  ---------------
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:133:in `compile_and_converge_action'
    /root/chef-solo/local-mode-cache/cache/cookbooks/chef_hostname/resources/hostname.rb:200:in `block in after_created'
    /root/chef-solo/local-mode-cache/cache/cookbooks/chef_hostname/resources/hostname.rb:199:in `each'
    /root/chef-solo/local-mode-cache/cache/cookbooks/chef_hostname/resources/hostname.rb:199:in `after_created'
    /root/chef-solo/local-mode-cache/cache/cookbooks/host-setup/recipes/default.rb:13:in `from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'

  Relevant File Content:
  ----------------------
  /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:

   71:              run_action(notification.resource, notification.action, :before, resource)
   72:            end
   73:            resource.updated_by_last_action(false)
   74:          end
   75:        end
   76:
   77:        # Actually run the action for realsies
   78>>       resource.run_action(action, notification_type, notifying_resource)
   79:
   80:        # Execute any immediate and queue up any delayed notifications
   81:        # associated with the resource, but only if it was updated *this time*
   82:        # we ran an action on it.
   83:        if resource.updated_by_last_action?
   84:          run_context.immediate_notifications(resource).each do |notification|
   85:            Chef::Log.info("#{resource} sending #{notification.action} action to #{notification.resource} (immediate)")
   86:            run_action(notification.resource, notification.action, :immediate, resource)
   87:          end

  Platform:
  ---------
  x86_64-linux
```

I think it's because the `dbus` package is missing. See [here](http://serverfault.com/questions/685837/how-to-set-the-hostname-for-a-debian-jessie-system) and [here](https://github.com/joyent/centos-lx-brand-image-builder/issues/5#issuecomment-216962653).

I'm currently (because of this) installing it myself, but I think this cookbook should install its dependencies itself. What do you think?

**Comment by aried3r** [comment]
I tested this locally using Vagrant and the current Ubuntu 16.04.1 LTS image and it seems to work. It might be my hoster missing this package in their image. I'm currently in contact with support and will verify this and close this issue should this be the case.

**Comment by aried3r** [comment]
Yup, issue of our hoster's Ubuntu image. Closing.
